name: PR reviewer

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write
  contents: write

jobs:
  build_and_test:
    name: Node Build & Test
    uses: ./.github/workflows/lib-node.yml
    permissions:
      actions: read
      id-token: write
      contents: write
    with:
      node-version: 20
